// @flow

export const APPLE_CN_CONTACT_SORT_ORDER_NONE = 0;
export const APPLE_CN_CONTACT_SORT_ORDER_DEFAULT = 1;
export const APPLE_CN_CONTACT_SORT_ORDER_GIVEN_NAME = 2;
export const APPLE_CN_CONTACT_SORT_ORDER_FAMILY_NAME = 3;
